# -*- coding: utf-8 -*-
"""Data Query and Retrieval System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5bB6ZO_rvptOLanFMvWd0XLmTs7OX-z
"""

!pip install pymongo
!pip install langchain-community
!pip install ctransformers


import csv
from pymongo import MongoClient
from pymongo.errors import ConnectionFailure
from langchain.llms import CTransformers  # For using a local LLM
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
import pandas as pd
import re  # Import the regular expression module


# 1. CSV Data Management
def load_csv_to_mongodb(csv_file_path, mongodb_uri, db_name, collection_name):
    """
    Loads data from a CSV file into a MongoDB collection.

    Args:
        csv_file_path (str): Path to the CSV file.
        mongodb_uri (str): MongoDB connection URI.
        db_name (str): Name of the database.
        collection_name (str): Name of the collection.
    """
    try:
        client = MongoClient(mongodb_uri)
        db = client[db_name]
        collection = db[collection_name]
        collection.delete_many({})  # Clear existing data in the collection

        with open(csv_file_path, 'r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            if not reader.fieldnames:
                raise ValueError("CSV file is empty or has no headers.")

            data = list(reader)  # Read all data into a list
            if not data:
                print("CSV file is empty. No data to insert.")
                return  # Exit if no data

            collection.insert_many(data)  # Insert the list of dictionaries
        print(f"Data from {csv_file_path} successfully loaded into MongoDB collection: {collection_name}")
    except ConnectionFailure as e:
        print(f"Error: Could not connect to MongoDB: {e}")
        raise  # Re-raise the exception for the calling function to handle
    except (FileNotFoundError, IOError) as e:
        print(f"Error: Could not read CSV file: {e}")
        raise
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        raise

# 2. Dynamic Query Generation using LLM
def generate_mongodb_query(user_input, llm):
    """
    Generates a MongoDB query using an LLM based on user input.

    Args:
        user_input (str): The user's query.
        llm: The language model.

    Returns:
        str: The generated MongoDB query.  Returns an empty string on failure.
    """
    prompt_template = """
    You are a helpful assistant that can generate MongoDB queries based on user input.

    Here are some examples of user input and corresponding MongoDB queries:

    User Input: "What are the products with a price greater than $50?"
    MongoDB Query: db.products.find({ "Price": { "$gt": 50 } })

    User Input: "Find all products with a rating below 4.5 that have more than 200 reviews."
    MongoDB Query: db.products.find({ "Rating": { "$lt": 4.5 }, "Reviews": { "$gt": 200 } })

     User Input: "Which products in the Electronics category have a rating of 4.5 or higher and are in stock?"
    MongoDB Query: db.products.find({ "Category": "Electronics", "Rating": { "$gte": 4.5 }, "Stock": true })

    User Input: "List products launched after January 1, 2022, in the Home & Kitchen or Sports categories with a discount of 10% or more, sorted by price in descending order."
    MongoDB Query: db.products.find({ "LaunchDate": { "$gt": "2022-01-01" }, "Category": { "$in": ["Home & Kitchen", "Sports"] }, "Discount": { "$gte": 0.1 } }).sort({ "Price": -1 })


    Now, generate a MongoDB query for the following user input:

    User Input: "{user_input}"

    MongoDB Query:
    """
    prompt = PromptTemplate(template=prompt_template, input_variables=["user_input"])
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    try:
        response = llm_chain.run(user_input=user_input)
        # Basic cleaning of the response (remove extra newlines, etc.)
        cleaned_response = response.strip()
        return cleaned_response
    except Exception as e:
        print(f"Error generating MongoDB query: {e}")
        return ""  # Return empty string on error

def execute_query(mongodb_uri, db_name, collection_name, query):
    """
    Executes a MongoDB query and fetches the data.

    Args:
        mongodb_uri (str): MongoDB connection URI.
        db_name (str): Name of the database.
        collection_name (str): Name of the collection.
        query (str): The MongoDB query to execute.

    Returns:
        list: The query results as a list of dictionaries, or None on error.
    """
    try:
        client = MongoClient(mongodb_uri)
        db = client[db_name]
        collection = db[collection_name]

        # Parse the query string to a python dict.  Handles nested structures.
        # Use a safer method to evaluate the string, to mitigate security risks.
        def convert_value(s):
            s = s.strip()
            if s.startswith('"') and s.endswith('"'):
                return s[1:-1] #remove quotes
            if s.isdigit():
                return int(s)
            try:
                return float(s)
            except ValueError:
                return s

        def parse_dict_string(s):
            s = s.strip()
            if not s.startswith('{') or not s.endswith('}'):
                return None
            s = s[1:-1] # remove curly braces
            parts = s.split(',')
            result = {}
            for part in parts:
                if ':' not in part:
                    continue
                key, value = part.split(':', 1)
                key = key.strip().strip('"')
                value = convert_value(value)
                result[key] = value
            return result

        def parse_query(query_string):
            # Very basic parsing, this will need to be expanded for full MongoDB query syntax
            query_string = query_string.strip()
            if not query_string.startswith("db."):
                return {}
            parts = query_string.split('.', 1) #remove "db."
            if len(parts) < 2:
                return {}
            parts = parts[1].split('.', 1)
            if len(parts) < 2:
                return {}
            method_name = parts[1].split('(')[0]
            if method_name != "find":
                return {}

            find_args_start = query_string.find('find(') + len('find(')
            find_args_end = query_string.rfind(')')
            if find_args_start == -1 or find_args_end == -1:
                return {}

            find_args_string = query_string[find_args_start:find_args_end]

            # handle empty find()
            if not find_args_string:
                return {}

            query_dict = parse_dict_string(find_args_string)
            if query_dict is None:
                return {}
            return query_dict

        # Parse the query string
        query_dict = parse_query(query)

        if not query_dict:
            print("Invalid query format.  Cannot execute.")
            return None

        results = list(collection.find(query_dict))  # Convert cursor to list
        return results
    except ConnectionFailure as e:
        print(f"Error: Could not connect to MongoDB: {e}")
        return None
    except Exception as e:
        print(f"Error executing query: {e}")
        return None

# 3. Data Retrieval and Presentation
def display_data(data):
    """
    Displays the data in a human-readable format.

    Args:
        data (list): The data to display (list of dictionaries).
    """
    if not data:
        print("No data to display.")
        return

    # Use pandas DataFrame for pretty printing
    df = pd.DataFrame(data)
    print(df.to_string(index=False))  # Display without index

def save_data_to_csv(data, filename="output.csv"):
    """
    Saves the data to a new CSV file.

    Args:
        data (list): The data to save (list of dictionaries).
        filename (str, optional): The name of the CSV file. Defaults to "output.csv".
    """
    if not data:
        print(f"No data to save to CSV file: {filename}")
        return

    try:
        df = pd.DataFrame(data)
        df.to_csv(filename, index=False, encoding='utf-8')
        print(f"Data successfully saved to CSV file: {filename}")
    except Exception as e:
        print(f"Error saving data to CSV file: {e}")

def get_llm():
    """
    Initializes and returns the language model (CTransformers).  This function
    centralizes the LLM initialization.
    """
    model_path = "llama-2-7b-chat.ggmlv3.q4_0.bin"  # Or your chosen model
    try:
        llm = CTransformers(model=model_path, model_type="llama")
        return llm
    except Exception as e:
        print(f"Error loading the language model: {e}")
        return None

def main():
    """
    Main function to run the data query and retrieval system.
    """
    csv_file_path = "products.csv"  # Replace with your CSV file
    mongodb_uri = "mongodb://localhost:27017/"  # Replace with your MongoDB URI
    db_name = "mydatabase"  # Replace with your database name
    collection_name = "products"  # Replace with your collection name

    # Load CSV data into MongoDB
    try:
        load_csv_to_mongodb(csv_file_path, mongodb_uri, db_name, collection_name)
    except Exception:
        print("Failed to load CSV data into MongoDB.  Exiting.")
        return  # Exit if CSV loading fails

    llm = get_llm()  # Get the LLM instance
    if llm is None:
        print("Failed to initialize the language model. Exiting.")
        return  # Exit if LLM initialization fails

    queries_generated = [] # List to store the queries

    # User interaction loop
    while True:
        user_input = input("Enter your query (or 'exit' to quit): ")
        if user_input.lower() == 'exit':
            break

        query = generate_mongodb_query(user_input, llm)
        if not query:
            print("Failed to generate a valid MongoDB query. Please try again.")
            continue  # Go back to the beginning of the loop

        print(f"Generated MongoDB Query: {query}")
        queries_generated.append(f"User Input: {user_input}\nMongoDB Query: {query}\n") # Append the query

        results = execute_query(mongodb_uri, db_name, collection_name, query)
        if results is None:
            print("Failed to execute the query or retrieve data.")
            continue  # Go back to the beginning of the loop

        if not results:
            print("No matching data found.")
            continue

        # Present the data
        display_option = input("Do you want to (d)isplay the data or (s)ave it to a CSV file? (d/s): ").lower()
        if display_option == 'd':
            display_data(results)
        elif display_option == 's':
            save_file_name = input("Enter the name of the CSV file to save (e.g., results.csv): ")
            save_data_to_csv(results, save_file_name)
        else:
            print("Invalid option.  Displaying data.")
            display_data(results)

    # Save all generated queries to a file
    with open("queries_generated.txt", "w") as f:
        f.write("\n".join(queries_generated))
    print("Exiting...")

def create_sample_csv():
    """
    Creates a sample CSV file (products.csv) for testing.
    """
    data = [
        {"Product ID": 101, "Name": "Laptop", "Price": 1200, "Category": "Electronics", "Rating": 4.8, "Reviews": 300, "Brand": "Dell", "Stock": True, "Discount": 0.15, "LaunchDate": "2022-03-15"},
        {"Product ID": 102, "Name": "Smartphone", "Price": 800, "Category": "Electronics", "Rating": 4.6, "Reviews": 250, "Brand": "Samsung", "Stock": True, "Discount": 0.10, "LaunchDate": "2022-02-20"},
        {"Product ID": 103, "Name": "T-Shirt", "Price": 25, "Category": "Clothing", "Rating": 4.2, "Reviews": 100, "Brand": "Nike", "Stock": True, "Discount": 0.05, "LaunchDate": "2022-05-01"},
        {"Product ID": 104, "Name": "Running Shoes", "Price": 100, "Category": "Sports", "Rating": 4.5, "Reviews": 200, "Brand": "Nike", "Stock": True, "Discount": 0.0, "LaunchDate": "2022-04-01"},
        {"Product ID": 105, "Name": "Coffee Maker", "Price": 75, "Category": "Home & Kitchen", "Rating": 4.7, "Reviews": 150, "Brand": "Sony", "Stock": True, "Discount": 0.0, "LaunchDate": "2022-01-15"},
        {"Product ID": 106, "Name": "Headphones", "Price": 150, "Category": "Electronics", "Rating": 4.9, "Reviews": 400, "Brand": "Sony", "Stock": True, "Discount": 0.20, "LaunchDate": "2022-06-01"},
        {"Product ID": 107, "Name": "Blender", "Price": 100, "Category": "Home & Kitchen", "Rating": 4.4, "Reviews": 120, "Brand": "Generic", "Stock": True, "Discount": 0.0, "LaunchDate": "2021-11-01"},
        {"Product ID": 108, "Name": "Soccer Ball", "Price": 30, "Category": "Sports", "Rating": 4.0, "Reviews": 80, "Brand": "Adidas", "Stock": True, "Discount": 0.0, "LaunchDate": "2023-01-01"},
        {"Product ID": 109, "Name": "Gaming Mouse", "Price": 70, "Category": "Electronics", "Rating": 4.3, "Reviews": 180, "Brand": "Logitech", "Stock": True, "Discount": 0.05, "LaunchDate": "2023-03-01"},
        {"Product ID": 110, "Name": "Cookware Set", "Price": 200, "Category": "Home & Kitchen", "Rating": 4.6, "Reviews": 220, "Brand": "T-fal", "Stock": True, "Discount": 0.10, "LaunchDate": "2022-09-01"},
    ]

    try:
        df = pd.DataFrame(data)
        df.to_csv("products.csv", index=False, encoding='utf-8')
        print("Sample CSV file 'products.csv' created successfully.")
    except Exception as e:
        print(f"Error creating sample CSV file: {e}")

if __name__ == "__main__":
    create_sample_csv() # Create sample CSV.
    main()